/* soapcalcProxy.h
   Generated by gSOAP 2.7.8c from calc.h
   Copyright (C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapcalc_H
#define soapcalc_H
#include "soapH.h"
class calc
{   public:
	struct soap *soap;
	const char *endpoint;
	calc()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns", "urn:calc", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	virtual ~calc() { if (soap) { soap_destroy(soap); soap_end(soap); soap_done(soap); soap_del(soap); } };
	virtual int ns__add(double a, double b, double *result) { return soap ? soap_call_ns__add(soap, endpoint, NULL, a, b, result) : SOAP_EOM; };
	virtual int ns__sub(double a, double b, double *result) { return soap ? soap_call_ns__sub(soap, endpoint, NULL, a, b, result) : SOAP_EOM; };
	virtual int ns__mul(double a, double b, double *result) { return soap ? soap_call_ns__mul(soap, endpoint, NULL, a, b, result) : SOAP_EOM; };
	virtual int ns__div(double a, double b, double *result) { return soap ? soap_call_ns__div(soap, endpoint, NULL, a, b, result) : SOAP_EOM; };
	virtual int ns__pow(double a, double b, double *result) { return soap ? soap_call_ns__pow(soap, endpoint, NULL, a, b, result) : SOAP_EOM; };
};
#endif
